//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvWeb.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class about_tb
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string about { get; set; }
        public string telephone { get; set; }
        public string adress { get; set; }
        public string picture { get; set; }
    }
}
