//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvWeb.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class education_tb
    {
        public int ID { get; set; }
        public string Header { get; set; }
        public string lowerHeader1 { get; set; }
        public string lowerHeader2 { get; set; }
        public string gno { get; set; }
        public string date { get; set; }
    }
}
