//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvWeb.Models.Entitiy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbWebPageEntities1 : DbContext
    {
        public DbWebPageEntities1()
            : base("name=DbWebPageEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<about_tb> about_tb { get; set; }
        public virtual DbSet<contact_tb> contact_tb { get; set; }
        public virtual DbSet<education_tb> education_tb { get; set; }
        public virtual DbSet<experience_tb> experience_tb { get; set; }
        public virtual DbSet<hobies_tb> hobies_tb { get; set; }
        public virtual DbSet<login_tb> login_tb { get; set; }
        public virtual DbSet<Skill_tb> Skill_tb { get; set; }
    }
}
